### ISSUE TITLE
A LICENSE perhaps?

### ISSUE THREAD

**Issue by tabletcorry** [jordansissel/puppet-examples#4]
Could we add a license to this repo?

If you reply with a preferred type, I can do the pull request for you. I tried to look at your other repositories, but you seem to use quite a few :)

**Comment by jordansissel** [comment]
hah, indeed. I CHOOSE....

Something. I'll push one shortly.

**Comment by tabletcorry** [comment]
Cool, thanks!

I have been on a license file kick since reading http://blog.nig.gl/post/48445125606/finding-unlicensed-repos-on-github recently. Thanks for the great examples for puppet!

**Comment by jordansissel** [comment]
![2013-05-04-220836](https://f.cloud.github.com/assets/131818/463236/dd3eb882-b541-11e2-9e1d-3551abd94615.jpg)

**Comment by tabletcorry** [comment]
![i-775shxk-m](https://f.cloud.github.com/assets/456754/463241/a69c0b9e-b542-11e2-85f1-1e414524c23f.jpg)
